-- Query to get the main requirement in the challenge  to point 1 and 2
WITH 
redemp
AS 
(
  -- Getting the Maximum item for Retailer 300 partitioned by redemptiondate and ordered by createdatetime in descending way
  -- taking in consideration only the redemptiondates between the required dates ('2023-10-30' and '2023-11-05'
  SELECT
    redemptionDate,
    redemptionCount,
    createDateTime,
    ROW_NUMBER() OVER(PARTITION BY redemptionDate ORDER BY createDateTime DESC) AS rn
  FROM `asymmetric-bank-468816-n9.testing.tblRedemptions-ByDay`
  WHERE retailerId = 300
    AND redemptionDate BETWEEN '2023-10-30' AND '2023-11-05'   
),
dates as 
(
  -- Taking all the dates availables in the date range required, the best way is to create a time dimension to take the correct dates
  -- but for the challenge I take in consideration the universe of dates related to the main table and works.
  SELECT DISTINCT redemptionDate
  FROM `asymmetric-bank-468816-n9.testing.tblRedemptions-ByDay`
  WHERE redemptionDate BETWEEN '2023-10-30' AND '2023-11-05'
),
product
as   
(
  -- Only in this part is filtered every row with the row number = 1 to guarantee  the must recent redemption 
  SELECT
    redemptionDate,
    redemptionCount
  FROM redemp
  WHERE rn = 1
  ORDER BY redemptionDate
)
-- Join between dates (all universe in the range) and product (all data related with the requirement)
SELECT
  dates.redemptionDate,
  COALESCE(product.redemptionCount,0) AS redemptionCount    -- Applying 0 to all null values in the universe
FROM dates
LEFT JOIN product 
  ON dates.redemptionDate=product.redemptionDate
ORDER BY 1 DESC;


--  Query to get the answers 3 and 4 of requirements after to check the result set generated by the first query
--  The mayor redemption count is with redemptiondate 2023-11-04  for 5224  and the createddatetime related is 2023-11-05 11:00:00   --point 3   subpoint a
--  The minor redemption count is with redemptiondate 2023-11-02  for  null or 0  and the createddatetime does not exist        --point 3   subpoint b
SELECT
    redemptionDate,
    redemptionCount,
    createDateTime,
    ROW_NUMBER() OVER(PARTITION BY redemptionDate ORDER BY createDateTime DESC) AS rn
  FROM `asymmetric-bank-468816-n9.testing.tblRedemptions-ByDay`
  WHERE retailerId = 300
    AND redemptionDate BETWEEN '2023-10-30' AND '2023-11-05'  
    AND redemptionDate='2023-11-04' OR redemptionDate='2023-11-02';

--  Alternative query to solve the problem      point 4
with dates as 
(
  select distinct redemptionDate
  from `asymmetric-bank-468816-n9.testing.tblRedemptions-ByDay`
  where redemptionDate between '2023-10-30' and '2023-11-05' 
),
maximum_
as 
(
  select dates.redemptionDate, trbd.retailerId,max(id) max_id
  from  `asymmetric-bank-468816-n9.testing.tblRedemptions-ByDay` trbd
  right join dates on dates.redemptionDate=trbd.redemptionDate   and trbd.retailerId=300  
  group by redemptionDate,retailerId
)
select 
  maximum_.redemptionDate,
  coalesce(trbd1.redemptionCount,0) as redemptionCount
from `asymmetric-bank-468816-n9.testing.tblRedemptions-ByDay`  trbd1
right join maximum_  on maximum_.max_id=trbd1.id
order by maximum_.redemptionDate desc